### PR TITLE
Upgrade to Angular 13

### PR DESCRIPTION
**Pull request by venraij**
- Updated to support Angular 13
- Adds aria-describedby via the descibedBy option
- Adds CI/CD testing with github actions

### CODE REVIEW

**Comment by sagrawal31** [comment]
Thanks, @venraij for the efforts. @tanansatpal do you mind reviewing and merging this. This is very critical to upgrade to Angular 13.

**Comment by sagrawal31** [comment]
@venraij, did you release your updated package somewhere on npm?

**Comment by venraij** [comment]
> @venraij, did you release your updated package somewhere on npm?
> 
> 

No not yet, but will probibly dp that today.

**Comment by sagrawal31** [comment]
Thanks @venraij

**Comment by venraij** [comment]
@sagrawal31 here is the package https://www.npmjs.com/package/ngx-mat-intl-tel-input-angular-13

**Comment by sagrawal31** [comment]
Thanks a ton, @venraij. I'm gonna check it out.

**Review by tanansatpal — APPROVED** [review]

**Comment by Wlada** [comment]
Can you publish version 4.2.0 to the NPM? Thanks

**Pull request merged**
