### PR TITLE
If an existing number is present, use it to determine selected country

### PR DESCRIPTION
**Pull request by skidvd**

### CODE REVIEW

**Comment by skidvd** [comment]
A bit more information regarding the specific situation that this PR endeavors to resolve.  If an existing phone number's value is set via the FormBuilder during reactive form creation, the country selection does not match the phone number without this PR.  With this PR, it does correctly set the country.

**Comment by tanansatpal** [comment]
Hi @skidvd, the required functionality is already working. Can you provide the specific case where this is not working. Preferably the code which for using the field.

**Comment by skidvd** [comment]
I left a comment on the PR about this.

The specific case which is NOT working without this PR is as follows.

 If an existing phone number's value is set via the FormBuilder during
reactive form creation, the country selection does not match the phone
number without this PR. With this PR, it does correctly set the country.

So for example, the following code from a controller will NOT show the
proper selected country (without the PR) if this.phoneNumber contains a
valid value.

constructor(....) {

this.form = this.fb.group({
  phoneNumber: [this.phoneNumber, Validators.required]
});

}

With my PR, it works in both this case as well as the other cases where it
is specified only after initial form creation.

BTW, @https://github.com/bdavies also confirmed this bug as well.

**Comment by elyas-bhy** [comment]
Can we please get this PR merged?

**Comment by skidvd** [comment]
I have updated this PR to additionally include support for Angular 8.  I'd love to get this merged into the baseline please.

**Pull request merged**
