### PR TITLE
update - package.json : enhanced version

### PR DESCRIPTION
**Pull request by rbalet**
Change from `~` to `^` to make it accept every v13 version & to avoid having to `--force` while downloading it.

### CODE REVIEW

**Comment by christophe-mailfert** [comment]
Does this file will be merged one day ?

**Comment by k-matti** [comment]
Please merge this PR Asap

**Comment by dereekb** [comment]
@tanansatpal could you take a look at this, or how can I help in getting it approved?

**Review by khumbal — APPROVED** [review]

**Comment by coolpot** [comment]
when can this be merged?

**Comment by AqibAurangzeb** [comment]
@tanansatpal @khumbal as this has been approved can it be merged in? Having same issue.

**Comment by rubenbasco** [comment]
Please merge this @khumbal

**Comment by coolpot** [comment]
Mergy Mergy @khumbal

**Comment by AntoineBouquet** [comment]
+1

**Comment by itstueben** [comment]
is anyone of the maintainers here to merge this PR?

**Comment by koshtiankit** [comment]
@tanansatpal  Please merge this PR Asap and update

**Pull request merged**
